unique_ids:
  assets:
    standard-page.html: UVK3NP4YC7PTE2DVRAAF5PEPZTR62YYF
    theme.css: UPVDGRD25D4FAYVUMMG2LSRXPKHBH3AO
  forms:
    Form1: IV3KZ55UTIW6RU3D2SJ75OKX5A3RJ2PE
  modules: {}
  scripts: {}
  server_modules: {}
